packages:
  - docs
  - packages/**
  - samples/*
  - samples/*/fragments/*
  - samples/node-servers/**/*

catalog:
  '@cloudflare/workers-types': 4.20250224.0
  '@playwright/test': 1.54.2
  typescript: 5.5.4
  vite: 6.0.7
  vitest: ^3.0.5
  wrangler: 3.109.3

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
  - 'writable-dom'
