import type { ExecutionContext } from "@cloudflare/workers-types";
import { createRequestHandler } from "@react-router/cloudflare";
import type { ServerBuild } from "react-router";

type Env = {
  ASSETS?: Fetcher;
  DEV_MODE?: string;
};

type CloudflareEvent<Environment> = {
  request: Request;
  env: Environment;
  waitUntil: ExecutionContext["waitUntil"];
  passThroughOnException: ExecutionContext["passThroughOnException"];
};

const handlerCache = new Map<string, ReturnType<typeof createRequestHandler>>();

function getRequestHandler(mode: string) {
  let handler = handlerCache.get(mode);
  if (!handler) {
    handler = createRequestHandler({
      // @ts-expect-error - the server build file is generated by `react-router build`
      build: () => import("./build/server/index.js") as Promise<ServerBuild>,
      mode,
    });
    handlerCache.set(mode, handler);
  }

  return handler;
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const isDev = env.DEV_MODE === "true";
    const mode = isDev ? "development" : "production";

    if (!isDev && env.ASSETS) {
      const assetResponse = await env.ASSETS.fetch(request.url, request.clone());
      if (assetResponse.status !== 404) {
        return assetResponse;
      }
    }

    const requestHandler = getRequestHandler(mode);

    const cloudflareEvent: CloudflareEvent<Env> = {
      request,
      env,
      waitUntil: ctx.waitUntil.bind(ctx),
      passThroughOnException: ctx.passThroughOnException.bind(ctx),
    };

    return requestHandler(cloudflareEvent);
  },
};
