[build]
  base = 'e2e/pierced-react-netlify'
  publish = "dist"

[dev]
  publish = "dist"
  port=8788
  # command="echo \"already built\""
  framework='#static'

[functions]
  deno_import_map = "./import_map.json"
