name: Deploy Docs Site

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd docs
          pnpm install

      - name: Build project
        run: |
          cd docs
          pnpm --filter web-fragments-docs build

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          npx wrangler pages publish ./docs/dist \
            --project-name=<PROJECT_NAME> \
            --branch=main
