name: Deploy Docs Site

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
      - 'pnpm-lock.yaml'
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'docs/'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0

      - name: Install Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          npx wrangler pages publish ./docs/dist \
            --project-name=web-fragments-dev \
            --branch=main
